config/routes.rb
Rails.application.routes.draw do
  
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'

  resources :microposts
  resources :users

  root 'static_pages#home'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
	belongs_to :user
	validates :content, length: {maximum: 140}
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :microposts
	has_attached_file :image, :styles =>{ large: "600x600>", medium: "300x300>", thumb: "200x200#"}
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@users = User.all.order(score: :desc);
  	@leader = @users[0];
  end

  def help
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all;
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created. #{@user.image.url}' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :score, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(provided="")
		msg = "title " + provided;
		flash.now[:notice] = msg;
		if provided.empty?
			title = "ClujPoker League";
		else
			title =  "ClujPoker League | " +provided;
		end
	end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %title= full_title(yield(:title))
    .jumbotron
      #jumbo_title
        %h1 ClujPoker League
    %nav.navbar.navbar-inverse
      .container-fluid
        .navbar-inner
          .container
            %ul.nav.navbar-nav
              %li
                %a{:href => '/static_pages/home'} Results
              %li
                %a{:href => '/users'}Users
              %li
                %a{:href => '/users/new'}Add user
  %body
    = yield
    :javascript
      $(document).ready(function(){
      		var path = window.location.pathname;
      		$('.nav.navbar-nav li a').each(function(){
      			if($(this).attr('href')==path){
      				$(this).parent().addClass('active')
      			}
      		})
      	}
      );

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Microposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/static_pages/about.html.haml
-provide(:title, "About")
%h1 About
%p
  This web app is all about hobby, Texas Hold'em
  %strong as a sport
  , a competition. 
  %br 
    And this should be a new line
    %br Also this

app/views/static_pages/help.html.erb
-provide(:title, "Help")
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.haml
!!!
-provide(:title, "Results")
%html
  %body
    .container
      .row
        .col-xs-12.col-sm-3
        #list_title.col-xs-12.col-sm-6
          %h2 Overall results
          %table{:border => "1"}
            - @users.each_with_index do |user, index|
              - if index == 0
                %tr#overall_first
                  %td= "#{index+1}."
                  %td= "#{user.name}"
                  %td= "#{user.score}"
              - elsif index%2 == 0
                %tr#overall_par
                  %td= "#{index+1}."
                  %td= "#{user.name}"
                  %td= "#{user.score}"
              - else
                %tr#overall_impar
                  %td= "#{index+1}."
                  %td= "#{user.name}"
                  %td= "#{user.score}"
        #winner_field.col-xs-12.col-sm-3
          .col-xs-3.col-sm-12
          .col-xs-6.col-sm-12
            %h4.name=@leader.name
            = image_tag@leader.image.url, :class=>"img-responsive img-thumbnail"
            %h4.leader Leader
          .col-xs-3.col-sm-12

app/views/users/_form.html.haml
= form_for @user, :html => {:multipart => true} do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error") 
        prohibited this user from being saved
      %ul
        = @user.errors.full_messages.each do |message|
          %li= message

  .field#labels
    %strong= f.label :name
    = f.text_field :name
  .field#labels 
    %strong= f.label :email
    = f.text_field :email
  .field#labels
    %strong= f.label :score
    = f.text_field :score
  .field#labels
    %strong= f.label :image
    = f.file_field :image
  .actions
    = f.submit

app/views/users/edit.html.haml
%h1.field Editing User
= render 'form'

app/views/users/index.html.haml
-provide(:title, "Users")
%h1.field Listing Users

%table
  %thead
    %tr#labels
      %th Name
      %th Email
      %th Score
      %th{:colspan => '3'}
  %tbody
  - @users.each do |user|
    %tr#user-name
      %td= user.name
      %td= user.email
      %td= user.score
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, method: :delete, data: {confirm: 'Are you sure?'}
%p
%p#notice= notice
%p

app/views/users/new.html.haml
- provide(:title, "Add User");
%h1.field New User

= render 'form'

app/views/users/show.html.haml
%p#notice
  = notice

%table
  %tr
    %td#labels.col-md-1
      Name:
    %td#user-name.col-md-11
      = @user.name
  %tr
    %td#labels.col-md-1
      Email:
    %td#user-name.col-md-11
      = @user.email
  %tr
    %td#labels.col-md-1
      Score:
    %td#user-name.col-md-11
      = @user.score
  %tr
    %td#labels.col-md-1
      Image
    %td
      = image_tag @user.image.url(:medium);

%div.low-buttons.col-md-3
  .col-md.6= link_to 'Edit', edit_user_path(@user)
  .col-md.6= link_to 'Back', user_path